version: '2'

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.3.8
    container_name: etcd1
    command: etcd -name etcd1 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - web

networks:
  web:
    external:
      name: gomicro